spring:
  application:
    name: testweb
  datasource:
    driver-class-name: org.postgresql.Driver
    password: admin
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
server:
  servlet:
    context-path: "/test"
